=== KRMAssociatesInc/eHMP/JAR/xmltooling-1.3.2-1/schema/xmltooling-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
    xmlns:xt="http://www.opensaml.org/xmltooling-config"
    targetNamespace="http://www.opensaml.org/xmltooling-config">

    <element name="XMLTooling" type="xt:XMLToolingType" />
    <complexType name="XMLToolingType">
        <sequence>
            <element ref="xt:ObjectProviders" minOccurs="0"/>
            <element ref="xt:ValidatorSuites" minOccurs="0" />
            <element ref="xt:IDAttributes" minOccurs="0" />
        </sequence>
    </complexType>

    <element name="ObjectProviders" type="xt:ObjectProvidersType" />
    <complexType name="ObjectProvidersType">
        <sequence>
            <element ref="xt:ObjectProvider" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <element name="ObjectProvider" type="xt:ObjectProviderType" />
    <complexType name="ObjectProviderType">
        <sequence>
            <element ref="xt:BuilderClass" />
            <element ref="xt:MarshallingClass" />
            <element ref="xt:UnmarshallingClass" />
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="qualifiedName" type="QName" use="required" />
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="BuilderClass" type="xt:ClassType" />
    <element name="MarshallingClass" type="xt:ClassType" />
    <element name="UnmarshallingClass" type="xt:ClassType" />
    <complexType name="ClassType">
        <sequence>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="className" type="string" use="required" />
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="ValidatorSuites" type="xt:ValidatorSuitesType" />
    <complexType name="ValidatorSuitesType">
        <sequence>
            <element ref="xt:ValidatorSuite" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <element name="ValidatorSuite" type="xt:ValidatorSuiteType"/>
    <complexType name="ValidatorSuiteType">
        <sequence>
            <element ref="xt:Validator" maxOccurs="unbounded" />
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>
        
        <attribute name="id" type="string" use="required" />
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>
    
    <element name="Validator" type="xt:ValidatorType"/>
    <complexType name="ValidatorType">
        <complexContent>
            <extension base="xt:ClassType">
                <attribute name="qualifiedName" type="QName" use="required" />
            </extension>
        </complexContent>
    </complexType>
    
    <element name="IDAttributes" type="xt:IDAttributesType" />
    <complexType name="IDAttributesType">
        <sequence>
            <element ref="xt:IDAttribute" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <element name="IDAttribute" type="QName"/>
</schema>

=== KRMAssociatesInc/eHMP/lib/opensaml-2.5.1-1/saml2-metadata-ui-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

	<!-- SAML 2.0 Protocol IdP Discovery Protocol Object providers -->
	<ObjectProviders>

		<!-- Description provider -->
		<ObjectProvider qualifiedName="mdui:Description">
			<BuilderClass className="org.opensaml.samlext.saml2mdui.impl.DescriptionBuilder"/>
			<MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DescriptionMarshaller"/>
			<UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DescriptionUnmarshaller"/>
		</ObjectProvider>
        
        <!-- DiscoHints provider -->
        <ObjectProvider qualifiedName="mdui:DiscoHints">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.DiscoHintsBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DiscoHintsMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DiscoHintsUnmarshaller"/>
        </ObjectProvider>
        
        <!-- Keywords provider -->
        <ObjectProvider qualifiedName="mdui:Keywords">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.KeywordsBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.KeywordsMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.KeywordsUnmarshaller"/>
        </ObjectProvider>

        <!-- DisplayName provider -->
        <ObjectProvider qualifiedName="mdui:DisplayName">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.DisplayNameBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DisplayNameMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DisplayNameUnmarshaller"/>
        </ObjectProvider>
        
        <!-- DomainHint provider -->
        <ObjectProvider qualifiedName="mdui:DomainHint">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.DomainHintBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DomainHintMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.DomainHintUnmarshaller"/>
        </ObjectProvider>
        
        <!-- GeolocationHint provider -->
        <ObjectProvider qualifiedName="mdui:GeolocationHint">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.GeolocationHintBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.GeolocationHintMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.GeolocationHintUnmarshaller"/>
        </ObjectProvider>
        
        <!-- InformationURL provider -->
        <ObjectProvider qualifiedName="mdui:InformationURL">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.InformationURLBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.InformationURLMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.InformationURLUnmarshaller"/>
        </ObjectProvider>
        
        <!-- IPHint provider -->
        <ObjectProvider qualifiedName="mdui:IPHint">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.IPHintBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.IPHintMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.IPHintUnmarshaller"/>
        </ObjectProvider>
            
        <!-- Logo provider -->
        <ObjectProvider qualifiedName="mdui:Logo">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.LogoBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.LogoMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.LogoUnmarshaller"/>
        </ObjectProvider>
        
        <!-- PrivacyStatementURL provider -->
        <ObjectProvider qualifiedName="mdui:PrivacyStatementURL">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.PrivacyStatementURLBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.PrivacyStatementURLMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.PrivacyStatementURLUnmarshaller"/>
        </ObjectProvider>
        
        <!-- UIInfo provider -->
        <ObjectProvider qualifiedName="mdui:UIInfo">
            <BuilderClass className="org.opensaml.samlext.saml2mdui.impl.UIInfoBuilder"/>
            <MarshallingClass className="org.opensaml.samlext.saml2mdui.impl.UIInfoMarshaller"/>
            <UnmarshallingClass className="org.opensaml.samlext.saml2mdui.impl.UIInfoUnmarshaller"/>
        </ObjectProvider>

	</ObjectProviders>
</XMLTooling>

=== KRMAssociatesInc/eHMP/lib/openws-1.4.2-1/soap11-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<xt:XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
 xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xt="http://www.opensaml.org/xmltooling-config">
    
    <!-- SOAP 1.1 Object Providers -->
    <xt:ObjectProviders>
    
        <!-- Body -->
        <xt:ObjectProvider qualifiedName="soap11:Body">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.BodyBuilder" />
            <xt:MarshallingClass className="org.opensaml.ws.soap.soap11.impl.BodyMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.ws.soap.soap11.impl.BodyUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- Detail -->
        <xt:ObjectProvider qualifiedName="detail">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.DetailBuilder" />
            <xt:MarshallingClass className="org.opensaml.ws.soap.soap11.impl.DetailMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.ws.soap.soap11.impl.DetailUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- Envelope -->
        <xt:ObjectProvider qualifiedName="soap11:Envelope">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.EnvelopeBuilder" />
            <xt:MarshallingClass className="org.opensaml.ws.soap.soap11.impl.EnvelopeMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.ws.soap.soap11.impl.EnvelopeUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- Fault -->
        <xt:ObjectProvider qualifiedName="soap11:Fault">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.FaultBuilder" />
            <xt:MarshallingClass className="org.opensaml.ws.soap.soap11.impl.FaultMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.ws.soap.soap11.impl.FaultUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- faultcode -->
        <xt:ObjectProvider qualifiedName="faultactor">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.FaultActorBuilder" />
            <xt:MarshallingClass className="org.opensaml.xml.schema.impl.XSURIMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.xml.schema.impl.XSURIUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- faultcode -->
        <xt:ObjectProvider qualifiedName="faultcode">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.FaultCodeBuilder" />
            <xt:MarshallingClass className="org.opensaml.xml.schema.impl.XSQNameMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.xml.schema.impl.XSQNameUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- faultstring -->
        <xt:ObjectProvider qualifiedName="faultstring">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.FaultStringBuilder" />
            <xt:MarshallingClass className="org.opensaml.xml.schema.impl.XSStringMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.xml.schema.impl.XSStringUnmarshaller" />
        </xt:ObjectProvider>
        
        <!-- Header -->
        <xt:ObjectProvider qualifiedName="soap11:Header">
            <xt:BuilderClass className="org.opensaml.ws.soap.soap11.impl.HeaderBuilder" />
            <xt:MarshallingClass className="org.opensaml.ws.soap.soap11.impl.HeaderMarshaller" />
            <xt:UnmarshallingClass className="org.opensaml.ws.soap.soap11.impl.HeaderUnmarshaller" />
        </xt:ObjectProvider>
        
    </xt:ObjectProviders>

</xt:XMLTooling>

=== KRMAssociatesInc/eHMP/lib/opensaml-2.5.1-1/saml2-assertion-delegation-restriction-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:del="urn:oasis:names:tc:SAML:2.0:conditions:delegation" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

	<!-- SAML 2.0 Delegation Restriction Condition Object providers -->
	<ObjectProviders>

		<!-- Delegate provider -->
		<ObjectProvider qualifiedName="del:Delegate">
			<BuilderClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegateBuilder"/>
			<MarshallingClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegateMarshaller"/>
			<UnmarshallingClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegateUnmarshaller"/>
		</ObjectProvider>
		
		<!-- DelegationRestrictionType provider -->
		<ObjectProvider qualifiedName="del:DelegationRestrictionType">
			<BuilderClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegationRestrictionTypeBuilder"/>
			<MarshallingClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegationRestrictionTypeMarshaller"/>
			<UnmarshallingClass className="org.opensaml.samlext.saml2delrestrict.impl.DelegationRestrictionTypeUnmarshaller"/>
		</ObjectProvider>
		
	</ObjectProviders>
</XMLTooling>

=== KRMAssociatesInc/eHMP/JAR/openws-1.4.2-1/wspolicy-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns="http://www.opensaml.org/xmltooling-config">

    <!-- WS-Policy 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsp:All -->
        <ObjectProvider qualifiedName="wsp:All">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.AllBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AllMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AllUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsp:AppliesTo -->
        <ObjectProvider qualifiedName="wsp:AppliesTo">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.AppliesToBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AppliesToMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AppliesToUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsp:ExactlyOne -->
        <ObjectProvider qualifiedName="wsp:ExactlyOne">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.ExactlyOneBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.ExactlyOneMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.ExactlyOneUnmarshaller" />
        </ObjectProvider>

        <!-- wsp:Policy -->
        <ObjectProvider qualifiedName="wsp:Policy">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.PolicyBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsp:PolicyAttachment -->
        <ObjectProvider qualifiedName="wsp:PolicyAttachment">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.PolicyAttachmentBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyAttachmentMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyAttachmentUnmarshaller" />
        </ObjectProvider>

        <!-- wsp:PolicyReference -->
        <ObjectProvider qualifiedName="wsp:PolicyReference">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceUnmarshaller" />
        </ObjectProvider>

    </ObjectProviders>

</XMLTooling>

=== KRMAssociatesInc/eHMP/JAR/openws-1.4.2-1/wssecurity-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
    xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd"
    xmlns="http://www.opensaml.org/xmltooling-config">

    <!-- WS-Security 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsse:BinarySecurityToken -->
        <ObjectProvider qualifiedName="wsse:BinarySecurityToken">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenUnmarshaller" />
        </ObjectProvider>

        <!-- wsu:Created -->
        <ObjectProvider qualifiedName="wsu:Created">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.CreatedBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.CreatedMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.CreatedUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:Embedded -->
        <ObjectProvider qualifiedName="wsse:Embedded">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.EmbeddedBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.EmbeddedMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.EmbeddedUnmarshaller" />
        </ObjectProvider>

        <!-- wsse11:EncryptedHeader -->
        <ObjectProvider qualifiedName="wsse11:EncryptedHeader">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsu:Expires -->
        <ObjectProvider qualifiedName="wsu:Expires">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.ExpiresBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.ExpiresMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.ExpiresUnmarshaller" />
        </ObjectProvider>

        <!-- wsse11:Iteration -->
        <ObjectProvider qualifiedName="wsse11:Iteration">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.IterationBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.IterationMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.IterationUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:KeyIdentifier -->
        <ObjectProvider qualifiedName="wsse:KeyIdentifier">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.KeyIdentifierBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.KeyIdentifierMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.KeyIdentifierUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:Nonce -->
        <ObjectProvider qualifiedName="wsse:Nonce">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.NonceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.NonceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.NonceUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:Password -->
        <ObjectProvider qualifiedName="wsse:Password">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.PasswordBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.PasswordMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.PasswordUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:Reference -->
        <ObjectProvider qualifiedName="wsse:Reference">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.ReferenceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.ReferenceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.ReferenceUnmarshaller" />
        </ObjectProvider>

        <!-- wsse11:Salt -->
        <ObjectProvider qualifiedName="wsse11:Salt">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.SaltBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SaltMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SaltUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:Security -->
        <ObjectProvider qualifiedName="wsse:Security">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.SecurityBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SecurityMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SecurityUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:SecurityTokenReference -->
        <ObjectProvider qualifiedName="wsse:SecurityTokenReference">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsu:SignatureConfirmation -->
        <ObjectProvider qualifiedName="wsu:SignatureConfirmation">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationUnmarshaller" />
        </ObjectProvider>

        <!-- wsu:Timestamp -->
        <ObjectProvider qualifiedName="wsu:Timestamp">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.TimestampBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.TimestampMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.TimestampUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsse:TransformationParameters -->
        <ObjectProvider qualifiedName="wsse:TransformationParameters">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.TransformationParametersBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.TransformationParametersMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.TransformationParametersUnmarshaller" />
        </ObjectProvider>
        
        <!-- wsse:Username -->
        <ObjectProvider qualifiedName="wsse:Username">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.UsernameBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.UsernameMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.UsernameUnmarshaller" />
        </ObjectProvider>

        <!-- wsse:UsernameToken -->
        <ObjectProvider qualifiedName="wsse:UsernameToken">
            <BuilderClass
                className="org.opensaml.ws.wssecurity.impl.UsernameTokenBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wssecurity.impl.UsernameTokenMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wssecurity.impl.UsernameTokenUnmarshaller" />
        </ObjectProvider>

    </ObjectProviders>
    
    <IDAttributes>
        <IDAttribute>wsu:Id</IDAttribute>
    </IDAttributes>

</XMLTooling>

=== KRMAssociatesInc/eHMP/JAR/opensaml-2.5.1-1/saml2-ecp-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecp="urn:oasis:names:tc:SAML:2.0:profiles:SSO:ecp" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">
 
    <!-- SAML 2.0 ECP Object providers -->
    <ObjectProviders>
        
        <!-- Request -->
        <ObjectProvider qualifiedName="ecp:Request">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.RequestBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.RequestMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.RequestUnmarshaller"/>
        </ObjectProvider>
        
        <!-- Response -->
        <ObjectProvider qualifiedName="ecp:Response">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.ResponseBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.ResponseMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.ResponseUnmarshaller"/>
        </ObjectProvider>
        
        <!-- RelayState -->
        <ObjectProvider qualifiedName="ecp:RelayState">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.RelayStateBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.RelayStateMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.RelayStateUnmarshaller"/>
        </ObjectProvider>
 
    </ObjectProviders>
 </XMLTooling>
